### ISSUE TITLE
Setting MANGA_TAGGER_ADULT_RESULT to true breaks the container

### ISSUE THREAD

**Issue by Kazakuri** [MangaManagerORG/Manga-Tagger#7]
Turning on adult results via the environment variable throws an error trying to call `LOG.info` in `utils.py` which causes the service to restart in a loop:

```
2021-05-18 01:11:53,951 | MainThread 140687825038152 | MangaTaggerLib.database.Database | INFO - Establishing database connection...
2021-05-18 01:11:53,953 | MainThread 140687825038152 | MangaTaggerLib.database.Database | INFO - Database connection established!
2021-05-18 01:11:53,953 | MainThread 140687825038152 | MangaTaggerLib.utils.AppSettings | INFO - Download directory has been set as "/downloads"
Traceback (most recent call last):
  File "/app/Manga-Tagger/MangaTagger.py", line 4, in <module>
    MangaTaggerLib.main()
  File "/app/Manga-Tagger/MangaTaggerLib/MangaTaggerLib.py", line 34, in main
    AppSettings.load()
  File "/app/Manga-Tagger/MangaTaggerLib/utils.py", line 236, in load
    LOG.info('Adult result enabled.')
NameError: name 'LOG' is not defined   
```

Looking at the other code in the file, I suspect that it should be `cls._log.info` instead of `LOG.info`, but I haven't tested that yet.

**Comment by Kazakuri** [comment]
Awesome, thanks for the quick fix!
I only have the one series in my library that requires the adult setting, but the unstable Docker image was able to enable that setting and pull in the metadata for that series.

I'll let you close the issue when you merge in the branch.
