### ISSUE TITLE
Error on Titles With Spaces When the Title is in the Chapter Name

### ISSUE THREAD

**Issue by Kazakuri** [MangaManagerORG/Manga-Tagger#8]
For example:
```
Koryuu nara Sude de Taosemasu kedo, Kore tte Joushiki janain desu ka -.- KORYUU NARA SUDE DE TAOSEMASU KEDO, KORE TTE JOUSHIKI JANAIN DESU KA Chapter 001.cbz
```

If the title of the series is in the chapter and that title has spaces I get this output: 

```
2021-05-18 00:56:27,961 | MTT-4 140112896375608 | MangaTaggerLib.MangaTaggerLib | DEBUG - delimiter: koryuu nara sude de taosemasu kedo, kore tte joushiki janain desu kachapter
2021-05-18 00:56:27,962 | MTT-4 140112896375608 | MangaTaggerLib.MangaTaggerLib | DEBUG - delimiter_index: 76
2021-05-18 00:56:27,962 | MTT-4 140112896375608 | MangaTaggerLib.task_queue.QueueWorker | ERROR - substring not found
Traceback (most recent call last):
  File "/app/Manga-Tagger/MangaTaggerLib/task_queue.py", line 188, in process
    MangaTaggerLib.process_manga_chapter(path, uuid.uuid1())
  File "/app/Manga-Tagger/MangaTaggerLib/MangaTaggerLib.py", line 65, in process_manga_chapter
    manga_details = filename_parser(filename, logging_info)
  File "/app/Manga-Tagger/MangaTaggerLib/MangaTaggerLib.py", line 147, in filename_parser
    i = chapter_title.index(delimiter) + delimiter_index
ValueError: substring not found
2021-05-18 00:56:27,963 | MTT-4 140112896375608 | MangaTaggerLib.task_queue.QueueWorker | WARNING - Manga Tagger is unfamiliar with this error. Please log an issue for investigation.
```

My guess is that it's because of [this section](https://github.com/Banh-Canh/Manga-Tagger/blob/ed777485da5a98ff5461df283cb1e319a0eb2e0c/MangaTaggerLib/MangaTaggerLib.py#L136-L139):

```python
        if 'chapter' in chapter_title:
            chapter_title = chapter_title.replace(' ', '')
            delimiter = f'{manga_title.lower()}chapter'
            delimiter_index = len(delimiter) + 1
```

The log shows it's using: 

```
koryuu nara sude de taosemasu kedo, kore tte joushiki janain desu kachapter
```

as the delimiter, but the since spaces are being removed from the chapter title first it should probably be using this instead:
```
koryuunarasudedetaosemasukedo,korettejoushikijanaindesukachapter
```

**Comment by Banh-Canh** [comment]
The section you mentionned was made "obsolete" since I reworked how the chapter_title was parsed. I forgot to remove it.
Manga-Tagger should only care about the chapter number and completely ignore any chapter name, manga name that are after the -.- delimiter.

Thanks for reporting the issue.
The fix for this error should be live on the unstable tagged docker image/dev branch if you want to try it.

**Comment by Kazakuri** [comment]
Once again thanks for the quick fix. The unstable Docker image fixed this and grabbed the proper metadata.
