### ISSUE TITLE
[BUG] Docker container is unable to read settings.json

### ISSUE THREAD

**Issue by ZhunCn** [MangaManagerORG/Manga-Tagger#9]
**OS**: Unraid 6.9.2 (Linux kernel 5.10.28)

**Manga Tagger Version:** Latest label on docker as of 5/22/2021 (reverting back to release-v1.2.1-alpha allows me to operate the container normally)

**Description of the issue:** Docker container is unable to read settings.json, not getting past initialization of the program.

**Manga Series:** N/A

**Screenshots (If applicable):** Environment Variables: [Screenshot from Unraid GUI](https://i.imgur.com/7HIjLSZ.png)

**Log File**: 
Log output from UNRAID
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
_ ()
| | ___ _ __
| | / __| | | / \
| | \__ \ | | | () |
|_| |___/ |_| \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid: 99
User gid: 100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Traceback (most recent call last):
File "/app/Manga-Tagger/MangaTagger.py", line 4, in <module>
MangaTaggerLib.main()
File "/app/Manga-Tagger/MangaTaggerLib/MangaTaggerLib.py", line 34, in main
AppSettings.load()
File "/app/Manga-Tagger/MangaTaggerLib/utils.py", line 46, in load
with open(settings_location, 'r+') as settings_json:
PermissionError: [Errno 13] Permission denied: '/app/Manga-Tagger/settings.json'
Traceback (most recent call last):
File "/app/Manga-Tagger/MangaTagger.py", line 4, in <module>
MangaTaggerLib.main()
File "/app/Manga-Tagger/MangaTaggerLib/MangaTaggerLib.py", line 34, in main
AppSettings.load()
File "/app/Manga-Tagger/MangaTaggerLib/utils.py", line 46, in load
with open(settings_location, 'r+') as settings_json:
PermissionError: [Errno 13] Permission denied: '/app/Manga-Tagger/settings.json'
```
The Traceback message continues to repeat as the program attempts to run.

**Comment by Banh-Canh** [comment]
Hi, thanks for reporting this error.
I wasn't able to reproduce it but I pushed an attempt to fix it on the dev branch. I'm not too familiar with UNRAID.
Can you try the unstable docker image and tell me if you still get this error ?

**Comment by ZhunCn** [comment]
Looks like it fixed the issue! Thanks. I do see these SyntaxWarnings, but I don't think they affect the run of the program from what I can see.
```
/app/Manga-Tagger/MangaTaggerLib/MangaTaggerLib.py:273: SyntaxWarning: "is" with a literal. Did you mean "=="?
if exceptions[manga_title]['format'] is "MANGA" or exceptions[manga_title]['format'] is "ONE_SHOT":
/app/Manga-Tagger/MangaTaggerLib/MangaTaggerLib.py:273: SyntaxWarning: "is" with a literal. Did you mean "=="?
if exceptions[manga_title]['format'] is "MANGA" or exceptions[manga_title]['format'] is "ONE_SHOT":
```

**Comment by Banh-Canh** [comment]
You can ignore these. They are related to a new feature (and a mistake of mine) I added in the dev branch, I'll get rid of it.

I will merge the dev branch into main after I have tested some more. Thanks for the feedback!
